version: '3.8'

services:
  api-service:
    build: .
    container_name: parkfinderApiService
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      
      - GCLOUD_PROJECT=demo-parkfinder
      - STORAGE_BUCKET=demo-parkfinder.appspot.com
      
      - FIRESTORE_EMULATOR_HOST=host.docker.internal:8080
      - FIREBASE_STORAGE_EMULATOR_HOST=host.docker.internal:9199

      - JWT_SECRET=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9... (sesuaikan)
      - JWT_EXPIRES_IN=1d

    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json
    extra_hosts:
      - "host.docker.internal:host-gateway"