version: '3.8'

services:
  api-service:
    build: .
    container_name: parkfinderApiService
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - REDIS_URL=
      - FIRESTORE_EMULATOR_HOST=host.docker.internal:8080
      - FIREBASE_AUTH_EMULATOR_HOST=host.docker.internal:9099
      - FIREBASE_STORAGE_EMULATOR_HOST=host.docker.internal:9199
      
    extra_hosts:
      - "host.docker.internal:host-gateway"