version: '3.8'

services:
  api-service:
    build: .
    container_name: parkfinderApiService
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      
      - GCLOUD_PROJECT=demo-parkfinder
      - STORAGE_BUCKET=demo-parkfinder.appspot.com
      
      - FIRESTORE_EMULATOR_HOST=host.docker.internal:8080
      - FIREBASE_STORAGE_EMULATOR_HOST=host.docker.internal:9199

      - JWT_SECRET=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE3NzAyMjU0NjIsImV4cCI6MTgwMTc2MTQ2MiwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsIkdpdmVuTmFtZSI6IkpvaG5ueSIsIlN1cm5hbWUiOiJSb2NrZXQiLCJFbWFpbCI6Impyb2NrZXRAZXhhbXBsZS5jb20iLCJSb2xlIjpbIk1hbmFnZXIiLCJQcm9qZWN0IEFkbWluaXN0cmF0b3IiXX0.Hj7ZqxjnfM8j22msTUglLWEun5q0XEF5oEH6yU07pxM
      - JWT_EXPIRES_IN=1d

    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json
    extra_hosts:
      - "host.docker.internal:host-gateway"